### ISSUE TITLE
Document that users should use `-c opt` when going into production

### ISSUE THREAD

**Issue by allada** [allada/turbo-cache#110]
If the user just compiles using `bazel build //cas` it will result in a very slow binary. This is because of the way rust compiles by default and rust is extremely slow in non-optimized binaries.

We can simply update the readme to tell users to use `-c opt` when building for production.

**Comment by chrisstaite-menlo** [comment]
You mean I've been running the slow version?  I can't imagine it going faster 😆 !

**Comment by allada** [comment]
Yes, and I also found that gzip is by far the slowest component taking like 70% of the time.

**Comment by allada** [comment]
I did some more testing and found that with gzip disabled here's the results with the following:

1. Build `bazel build --config self_test //...` (populate cache)
2. `bazel clean --noasync && bazel build --config self_test //...` (repeated 10 times)

All the numbers are the `usr` time using the `time` function of the `cas` binary:
```
$ bazel build -c opt //cas
19.434

$ bazel build -c opt --@rules_rust//:extra_rustc_flags=--codegen=lto=thin //cas
18.279

$ bazel build -c opt --@rules_rust//:extra_rustc_flags=--codegen=lto=fat //cas
17.134
```

So enabling fatlto yields ~10% speed boost. It could be higher if you can assume that most of the time data will be downloaded from the CAS instead of uploaded.
