### ISSUE TITLE
AC context lost in store trait

### ISSUE THREAD

**Issue by chrisstaite-menlo** [allada/turbo-cache#176]
When forwarding to an upstream AC store via a GrpcStore then it uses the AcServer.  However, if you wrap it in a fast_slow store, for example, to have a local cache, then you end up with it loosing the context and querying the CAS instead of the AC.

**Comment by allada** [comment]
I'm a bit confused by this. Do you have a config to showcase this?

**Comment by chrisstaite** [comment]
ac_utils::get_and_decode_digest calls StoreTrait::get_part_unchunked which calls GrpcStore::get_part which accesses the CAS at the endpoint rather than GrpcStore::get_action_result.

I might be misunderstanding this, but the CAS has two separate stores, one for CAS and one for AC and the only way to distinguish between them on the same endpoint is the service.

**Comment by allada** [comment]
I see what you mean. This is a very convoluted trail.

I think what we can do is put a flag on the GrpcStore's config and force it to only serve either AC or CAS, but not both.

Then all `get_part` will only use `get_action_result()` (similar for write()), or if CAS will only use the CAS's api.

**Comment by chrisstaite-menlo** [comment]
That would work.

**Comment by chrisstaite-menlo** [comment]
I had a hack around with this... we have an issue in that the `instance_name` is not passed through to `get_part`.  We could add it in?  I'm not sure it's the best solution or not...

**Comment by chrisstaite-menlo** [comment]
Oh, it's actually fine because the GrpcStore maps to a different `instance_name` anyway...

**Comment by chrisstaite** [comment]
Reading https://chromium.googlesource.com/infra/goma/server/+/refs/tags/v0.0.5/remoteexec/adapter.go I think that the CacheLookupScheduler is only required because of this bug

**Comment by chrisstaite-menlo** [comment]
Yup, the cache client isn't required with with fix.
