### ISSUE TITLE
Support building with only Cargo

### ISSUE THREAD

**Issue by allada** [allada/turbo-cache#231]
To make it more accessible we should support both cargo building and bazel building.

The major reason for this is because we should support windows, but in my experience it's quite difficult to get windows to work with bazel, so I'd like to just use cargo for such case.

**Comment by allada** [comment]
@aaronmondal We talked about this, and decided to actually go through with it :smile:

**Comment by aaronmondal** [comment]
Interesting! Do you already know how you'll handle the test libraries?

**Comment by allada** [comment]
Currently the plan is to only support the `cas` binary and all supporting libraries. After a PR to do that lands, maybe we can add test support.

**Comment by blasten** [comment]
@allada what issues did you encounter on Windows?

**Comment by allada** [comment]
> @allada what issues did you encounter on Windows?

I have a working version of the code that compiles and runs on windows. The major issue that I have is configuring bazel for windows is really rough. I'm sure it's something I'm doing, but I can't even compile bazel itself on windows, but I also have a version of windows that likely needs a fresh install.

You can see a lot of corner cases in windows here: https://bazel.build/configure/windows
