### ISSUE TITLE
Let's get goma going

### ISSUE THREAD

**Issue by kschzt** [allada/turbo-cache#241]
I'm trying to get turbo-cache working with goma. We're running a 512-core goma + buildbarn cluster with about a dozen builds per day. I got somewhere by just replacing buildbarn's CAS with turbo-cache, but would love to try running the whole thing on tc. 

I've got a turbo-cache scheduler, cas and worker running but currently stuck on this error from goma:

`exec call: error in check missing blobs: rpc error: code = Unimplemented desc = missing blobs: rpc error: code = Unimplemented`

I saw your PR @chrisstaite-menlo but a very similar configuration doesn't seem to do it for me yet.

**Comment by kschzt** [comment]
scheduler.json 
```
{
  "stores": {
    "GRPC_LOCAL_STORE": {
      "grpc": {
        "instance_name": "local",
        "endpoints": ["grpc://goma.example.com:58981"],
        "store_type": "CAS"
      }
    },
    "GRPC_LOCAL_AC_STORE": {
      "grpc": {
        "instance_name": "local",
        "endpoints": ["grpc://goma.example.com:58981"],
        "store_type": "AC"
      }
    }
  },
  "schedulers": {
    "MAIN_SCHEDULER": {
      "simple": {
        "supported_platform_properties": {
          "OSFamily": "Exact"
        }
      }
    }
  },
  "servers": [{
    "listen_address": "0.0.0.0:58982",
    "services": {
      "ac": {
        "local": {
          "ac_store": "GRPC_LOCAL_AC_STORE"
        }
      },
      "execution": {
        "local": {
          "cas_store": "GRPC_LOCAL_STORE",
          "scheduler": "MAIN_SCHEDULER",
        }
      },
      "capabilities": {
        "local": {
          "remote_execution": {
            "scheduler": "MAIN_SCHEDULER",
          }
        }
      }
    }
  }, 
  {
    "listen_address": "0.0.0.0:58983",
    "services": {
      "worker_api": {
        "scheduler": "MAIN_SCHEDULER",
      }
    }
  }]
}
```

cas.json
```
{
  "stores": {
    "CAS_MAIN_STORE": {
      "memory": {
        "eviction_policy": {
          "max_bytes": 80000000000
        }
      }
    },
    "AC_MAIN_STORE": {
      "memory": {
        "eviction_policy": {
          "max_bytes": 20000000000
        }
      }
    }
  },
  "servers": [{
    "listen_address": "0.0.0.0:58981",
    "services": {
      "cas": {
        "local": {
          "cas_store": "CAS_MAIN_STORE"
        }
      },
      "ac": {
        "local": {
          "ac_store": "AC_MAIN_STORE"
        }
      },
      "capabilities": {
        "local": {}
      },
      "bytestream": {
        "cas_stores": {
          "local": "CAS_MAIN_STORE"
        },
        "max_bytes_per_stream": 64000
      }
    }
  }]
}
```

worker.json
```
{
  "stores": {
    "GRPC_LOCAL_STORE": {
      "grpc": {
        "instance_name": "local",
        "endpoints": ["grpc://goma.example.com:58981"],
        "store_type": "CAS"
      }
    },
    "GRPC_LOCAL_AC_STORE": {
      "grpc": {
        "instance_name": "local",
        "endpoints": ["grpc://goma.example.com:58981"],
        "store_type": "AC"
      }
    },
    "WORKER_FAST_SLOW_STORE": {
      "fast_slow": {
        "fast": {
          "filesystem": {
            "content_path": "~/.cache/turbo-cache/data-worker-test/content_path-cas",
            "temp_path": "~/.cache/turbo-cache/data-worker-test/tmp_path-cas",
            "eviction_policy": {
              "max_bytes": 80000000000
            }
          }
        },
        "slow": {
          "ref_store": {
            "name": "GRPC_LOCAL_STORE"
          }
        }
      }
    }
  },
  "workers": [{
    "local": {
      "worker_api_endpoint": {
        "uri": "grpc://goma.example.com:58983"
      },
      "cas_fast_slow_store": "WORKER_FAST_SLOW_STORE",
      "ac_store": "GRPC_LOCAL_AC_STORE",
      "work_directory": "~/.cache/turbo-cache/work",
      "platform_properties": {
        "OSFamily": {
          "values": ["Linux"]
        }
      }
    }
  }],
  "servers": []
}
```

**Comment by kschzt** [comment]
Duh. Added the CAS into the scheduler config and am getting further!

**Comment by kschzt** [comment]
Sorry, I got it all to work with the proper routing in scheduler.json.

**Comment by chrisstaite-menlo** [comment]
I love the thought trail on this issue, it's just like mine :). I've been busy with other stuff, but I'll hopefully get round to finishing off the example Docker soon.  Out of interest, have you got a measure of how much better Turbo Cache is performing over your BuildBarn implementation?  Personally, I never got a functioning BuildBarn implementation to compare it to (I gave up before it was functional).

**Comment by kschzt** [comment]
@chrisstaite-menlo so I haven't got any hard measurements, so take this with a grain of salt :) 

The first build with a completely empty cache seemed to take a little bit longer and have lower TPS than with buildbarn, for some reason. However, after everything is in the CAS, the next build has somewhat better throughput and better overall time compared to buildbarn, although the difference is pretty small. I'm certainly not seeing a massive difference. 

My setup is roughly as follows: dedicated 32C/64T Windows Server building with goma, with local SSD, plus 4 x 32C/64T (total 256 cores currently, sometimes 512 with cloud) worker machines, also with local SSD, each with 128GB mem. One of the worker machines is also goma-server and TC/BB scheduler and CAS. The goma machine is on a 10Gbps uplink, the others on 1Gbps, connected via VLAN (at Hetzner). I'm seeing traffic _occasionally_ peak above 500Mbps to the Windows machine. I've also been increasing goma's concurrency parameters to minor effect (before TC). 

Although a build time of 16 minutes is pretty great for a full Chromium build with a full CAS, I'm still left wondering where there could be bottlenecks. In the warm-cache case, neither the CPUs nor the network are saturated (using `ninja -j1000`)...  The full cache is about 69G.

**Comment by allada** [comment]
It's in my to-do list to get the Goma example done. I have been busy with other things.

I'd be interested to research why the first build is slower, maybe the FUSE setup? I want to support a FUSE setup and native docker setup, but working with Investors lately, so my ability to work on this has been limited 😕

**Comment by allada** [comment]
FYI a fuse setup paired with dedup store should be super fast for initial builds.

**Comment by kschzt** [comment]
@allada I'm not using FUSE nor Docker, running everything straight on the OS; cross-compiling to Windows on Linux. So it's really quite straightforward. I'll continue to give both cases (TC/BB) more runs.

**Comment by kschzt** [comment]
I had to patch the goma-server before it would cross-compile for me: https://github.com/kschzt/goma-server

**Comment by kschzt** [comment]
Here are my current, working configs:

cas
```
{
  "stores": {
    "CAS_MAIN_STORE": {
      "fast_slow": {
        "fast": {
          "memory": {
            "eviction_policy": {
              "max_bytes": 10000000000
            }
          }
        },
        "slow": {
          "filesystem": {
            "content_path": "/home/rbe/rbe/tc/content_path-cas",
            "temp_path": "/home/rbe/rbe/tc/tmp_path-cas",
            "eviction_policy": {
              "max_bytes": 200000000000,
              "evict_bytes": 20000000000
            }
          }
        }
      }
    },

    "AC_MAIN_STORE": {
      "fast_slow": {
        "fast": {
          "memory": {
            "eviction_policy": {
              "max_bytes": 20000000000
            }
          }
        },
        "slow": {
           "filesystem": {
             "content_path": "/home/rbe/rbe/tc/content_path-cas_ac",
             "temp_path": "/home/rbe/rbe/tc/tmp_path-cas_ac",
             "eviction_policy": {
                "max_bytes": 20000000000,
             }
          }
        }
      }
    }
  },
  "servers": [{
    "listen_address": "0.0.0.0:58981",
      "services": {
        "cas": {
          "local": {
            "cas_store": "CAS_MAIN_STORE"
            }
        },
        "ac": {
          "local": {
          "ac_store": "AC_MAIN_STORE"
          }
      },
      "capabilities": {},
      "bytestream": {
        "cas_stores": {
          "local": "CAS_MAIN_STORE",
        },
        "max_bytes_per_stream": 64000, // 64kb.
      },
      "prometheus": {}
    }
  }]
}
```

scheduler
```
{
  "stores": {
    "GRPC_LOCAL_STORE": {
      "grpc": {
        "instance_name": "local",
        "endpoints": ["grpc://goma.example.com:58981"],
        "store_type": "CAS"
      }
    },
    "GRPC_LOCAL_AC_STORE": {
      "grpc": {
        "instance_name": "local",
        "endpoints": ["grpc://goma.example.com:58981"],
        "store_type": "AC"
      }
    }
  },
  "schedulers": {
    "MAIN_SCHEDULER": {
      "simple": {
        "supported_platform_properties": {
          "OSFamily": "Exact"
        }
      }
    }
  },
  "servers": [{
    "listen_address": "0.0.0.0:58982",
    "services": {
      "cas": {
        "local": {
          "cas_store": "GRPC_LOCAL_STORE"
        }
      },
      "ac": {
        "local": {
          "ac_store": "GRPC_LOCAL_AC_STORE"
        }
      },
      "bytestream": {
        "cas_stores": {
         "local": "GRPC_LOCAL_STORE"
        },
        "max_bytes_per_stream": 64000,
      },
      "execution": {
        "local": {
          "cas_store": "GRPC_LOCAL_STORE",
          "scheduler": "MAIN_SCHEDULER",
        }
      },
      "capabilities": {
        "local": {
          "remote_execution": {
            "scheduler": "MAIN_SCHEDULER",
          }
        }
      }
    }
  }, 
  {
    "listen_address": "0.0.0.0:58983",
    "services": {
      "worker_api": {
        "scheduler": "MAIN_SCHEDULER",
      }
    }
  }]
}```

worker
```
{
  "stores": {
    "GRPC_LOCAL_STORE": {
      "grpc": {
        "instance_name": "local",
        "endpoints": ["grpc://goma.example.com:58981"],
        "store_type": "CAS"
      }
    },
    "GRPC_LOCAL_AC_STORE": {
      "grpc": {
        "instance_name": "local",
        "endpoints": ["grpc://goma.example.com:58981"],
        "store_type": "AC"
      }
    },
    "WORKER_FAST_SLOW_STORE": {
      "fast_slow": {
        "fast": {
          "filesystem": {
            "content_path": "~/.cache/turbo-cache/data-worker-test/content_path-cas",
            "temp_path": "~/.cache/turbo-cache/data-worker-test/tmp_path-cas",
            "eviction_policy": {
              "max_bytes": 80000000000
            }
          }
        },
        "slow": {
          "ref_store": {
            "name": "GRPC_LOCAL_STORE"
          }
        }
      }
    }
  },
  "workers": [{
    "local": {
      "worker_api_endpoint": {
        "uri": "grpc://goma.example.com:58983"
      },
      "cas_fast_slow_store": "WORKER_FAST_SLOW_STORE",
      "ac_store": "GRPC_LOCAL_AC_STORE",
      "work_directory": "~/.cache/turbo-cache/work",
      "platform_properties": {
        "OSFamily": {
          "values": ["Linux"]
        }
      }
    }
  }],
  "servers": []
}
```

goma-server
```
./remoteexec_proxy \
	-port 5050 \
	-remoteexec-addr goma.example.com:58982 \
	-remote-instance-name local \
	-insecure-remoteexec \
	-service-account-json /home/ci/googlesa.json \
	-exec-config-file /home/ci/goma-config \
	-max-digest-cache-entries 200000000 \
	-allowed-users *@raybrowser.com \
	-redis-max-active-conns 400 \
	-redis-max-idle-conns 100
```

and the /home/ci/goma-config file something like this (mapping the compiler hashes for cross-compilation)
```
version_id:"1",
configs: [
        {
                dimensions: [ "os:win" ],
                cmd_descriptor: {
                        selector: {
                                name: "clang-cl",
                                version: "clang version 16.0.0 (https://chromium.googlesource.com/a/external/github.com/llvm/llvm-project 60809cd29308e78d662375e6957a2b1b85415def)",
                                target: "x86_64-pc-windows-msvc",
                                binary_hash: "e583ccc29101c6ddfd286ad9c93db7bb240ad4f372db0a5aa946d8c73e40dbd6",
                        },
                        setup: {
                                cmd_file: {
                                        path: "/home/goma/src/chromium/src/third_party/llvm-build/Release+Asserts/bin/clang-cl",
                                        is_executable: true,
                                },
                                path_type: 1,
                        },
                        emulation_opts: {
                                respect_client_include_paths: true,
                        },
                        cross: {
                                clang_need_target: true,
                                windows_cross: true,
                        },
                },
                build_info: {
                        creator: "kschzt",
                        hostname: "10.166.0.37",
                        toolchain: "clang-cl",
                },
                remoteexec_platform: {
                        properties: [ { name: "OSFamily", value: "Linux" } ],
                        rbe_instance_basename: "local",
                        has_nsjail: false,
                },
        }
]
}

```

**Comment by kschzt** [comment]
@allada Ahh, I think the lower throughput is because these workers saturate the CPU's more than buildbarn, which has a limited amount of workers (70 per 64 threads), so this takes load avg to 120+ where it should be below 64 - and then I see context deadline exceeded's. Maybe I should make a `precondition_script` to throttle workers?

**Comment by chrisstaite-menlo** [comment]
@kschzt oh, you 100% need to add a property modifier to limit the concurrency to 1 per core:
```
  "schedulers": {
    "MAIN_SCHEDULER": {
      "property_modifier": {
        "modifications": [
          {"Add": {"name": "cpu_count", "value": "1"}},
          {"Remove": "container-image"},
          {"Remove": "InputRootAbsolutePath"}
        ],
        "scheduler": {
          "simple": {
            "supported_platform_properties": {
              "OSFamily": "Exact",
              "cpu_count": "Minimum"
            }
          }
        }
      }
    }
  },
```

And on the worker:
```
      "platform_properties": {
        "OSFamily": {
          "values": ["Linux"],
        },
        "cpu_count": {
          "query_cmd": "nproc"
        },
      },
```

**Comment by kschzt** [comment]
I enabled the dedup store, the cpu_count stuff, and reduced -j to 512. It's better on the slow case, and set a new record of 13.5 mins in the warm-CAS case. Awesome!

**Comment by allada** [comment]
In your case, I'd try dedup store into a compression store. The dedup store should excell on incremental changes because object files usually are mostly the same between builds, and dedup store will attempt to only download the changes.

You may also want to play with enabling gzip transport compression. You need to be careful here because gzip takes a lot of cpu time on the server and client.

Using grpc store is probably pretty sub-optimal because you can't take advantage of a lot of optimizations. When I get home, I'm going to see about making an extension of grpc store to support things like dedup and compression store.

**Comment by kschzt** [comment]
Here's what I have for the CAS atm. I think I'm basically doing what you suggested? 
I'll increase the memory store size a bit as I have some more to spare.
I've got all 5 machines in the same DC, and they're all dedicated boxes. 

```
{
  "stores": {
    "FS_CONTENT_STORE": {
      "compression": {
        "compression_algorithm": {
          "LZ4": {}
        },
        "backend": {
          "filesystem": {
            "content_path": "/home/rbe/rbe/tc/content_path-cas",
            "temp_path": "/home/rbe/rbe/tc/tmp_path-cas",
            "eviction_policy": {
              "max_bytes": 200000000000, // 200gb
            }
          }
        }
      }
    },
    
    "CAS_MAIN_STORE": {
      "verify": {
        "backend": {
          "size_partitioning": {
            "size": 262144,
            "lower_store": {
              "ref_store": {
                "name": "FS_CONTENT_STORE"
              }
            },
            "upper_store": {
              "dedup": {
                "index_store": {
                  "fast_slow": {
                    "fast": {
                      "memory": {
                        "eviction_policy": {
                          "max_bytes": 20000000000, // 20gb
                        }
                      }
                    },
                    "slow": {
                      "filesystem": {
                        "content_path": "/home/rbe/rbe/tc/content_path-index",
                        "temp_path": "/home/rbe/rbe/tc/tmp_path-index",
                        "eviction_policy": {
                          "max_bytes": 120000000000, // 120gb
                        }
                      }
                    }
                  }
                },
                "content_store": {
                  "ref_store": {
                    "name": "FS_CONTENT_STORE"
                  }
                }
              }
            }
          }
        },
        "verify_size": true,
        "verify_hash": true
      }
    },


    "AC_MAIN_STORE": {
      "fast_slow": {
        "fast": {
          "memory": {
            "eviction_policy": {
              "max_bytes": 10000000000 // 10gb
            }
          }
        },
        "slow": {
           "filesystem": {
             "content_path": "/home/rbe/rbe/tc/content_path-cas_ac",
             "temp_path": "/home/rbe/rbe/tc/tmp_path-cas_ac",
             "eviction_policy": {
                "max_bytes": 20000000000, // 20gb
             }
          }
        }
      }
    }
  },
  "servers": [{
    "listen_address": "0.0.0.0:58981",
      "services": {
        "cas": {
          "local": {
            "cas_store": "CAS_MAIN_STORE"
            }
        },
        "ac": {
          "local": {
          "ac_store": "AC_MAIN_STORE"
          }
      },
      "capabilities": {},
      "bytestream": {
        "cas_stores": {
          "local": "CAS_MAIN_STORE",
        },
        "max_bytes_per_stream": 64000, // 64kb.
      },
      "prometheus": {}
    }
  }]
}

```

**Comment by chrisstaite-menlo** [comment]
I'd suggest removing the verify store, unless you think that it's likely the files on disk will degrade.

**Comment by kschzt** [comment]
Thanks a lot for your help gentlemen! Appreciate it. turbo-cache is working great now with goma. Better than buildbarn :) 🙏
