### ISSUE TITLE
Make platform properties available to entry point cmd

### ISSUE THREAD

**Issue by chrisstaite-menlo** [allada/turbo-cache#261]
There are cases (Chromium build for example) where the entry point command needs to get information from the platform properties.  Injecting these into the environment would not be ideal as it might make conflicts, but injecting them into placeholders in the entry point command would allow this information to be passed in in a configurable way and allow such actions as running within a property specified container image.

**Comment by allada** [comment]
Yeah, I 100% agree. I was planning on eventually injecting the platform properties into the action, but never got around to it.
