### ISSUE TITLE
benchmarks?

### ISSUE THREAD

**Issue by chancila** [allada/turbo-cache#96]
This isn't so much an issue but I'm curious if any benchmarks were done against any of the other popular bazel remote cache implementations

**Comment by allada** [comment]
Not yet, I'd been focusing on features thus far. Cache is going to mostly be limited by disk IO speed. I tried pretty hard to ensure we don't make copies of the data as much as possible.

I think this is the only implementation that supports compression or deduplication, so 1:1 comparison will be a bit tricky.
